// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: GamePlayProto.proto

#pragma warning disable 1591, 0612, 3021

namespace GamePlayProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public HeartBeat()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int TimeStamp { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
